### ISSUE TITLE
How to add another regex pattern?

### ISSUE THREAD

**Issue by stivens** [sgbush/buildoutputcolorizer#6]
Im using build tool which is not one of [gcc, clang, msvc, cmake].

How to add custom regex patterns without forking this repository?

EDIT: For clarity, there should be some sort of configuration on user-side IMHO

**Comment by sgbush** [comment]
Sorry for the long delay, I am just getting around to doing some maintenance.  This extension uses the VSCode-provided TextMate grammar facility, which uses only static grammar definitions.  This is great because there is no code required, but unfortunately also there is no user configuration.

If you have a use case which would be useful to the community (e.g., Meson, Bazel, ...) please raise another issue with the specific pattern/regex you propose.
